(global-unset-key (kbd "C-x p"))
(global-unset-key (kbd "C-x M-m"))
(global-set-key (kbd "C-x m") 'shell)
(global-set-key [f5] 'shell)
(global-unset-key [f12])
(global-set-key [f11] 'magit-status)
(global-set-key (kbd "C-<backspace>") 'backward-kill-word)
(global-set-key [remap other-window] 'other-window)
(global-set-key (kbd "C-c g") 'rgrep)
(global-set-key (kbd "S-SPC") 'helm-prelude)
(global-set-key [f6] 'toggle-truncate-lines)
(global-set-key [f2] 'winner-undo)
(global-set-key [f3] 'winner-redo)
